name: pizza_house
description: "Pizza House"

publish_to: 'none'

version: 0.0.1-dev.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Svg
  flutter_svg: ^2.0.2

  # Navigation
  go_router: ^14.2.8

  # UI
  shimmer: ^3.0.0

  # SM
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Generator
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.3.2
  build_verify: ^3.1.0

# Assets
flutter_gen:
  output: lib/generated
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/fonts/
   - assets/icons/
   - assets/images/
  
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka_medium.ttf
          weight: 500
        - asset: assets/fonts/fredoka_regular.ttf
          weight: 400
        - asset: assets/fonts/fredoka_light.ttf
          weight: 300
  

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/src/shared/localizations

